# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @export
mult <- function(v1, v2) {
    .Call(`_robord_mult`, v1, v2)
}

add <- function(x, y) {
    .Call(`_robord_add`, x, y)
}

rcpp_hello_world <- function() {
    .Call(`_robord_rcpp_hello_world`)
}

